### PR TITLE
When a model is deleted, gracefully handle it in any corresponding metrics def

### LINKED ISSUE #610: if I delete a model while it is profiling, the server throws an error
This is probably an easy fix.

Steps to reproduce:
- pull in a larger dataset like the nyc311 example
- try writing `select * from nyc311` in a model
- delete that model through the left sidebar before profiling has finished

When I do those steps, I get the following server error:

```
TypeError: Cannot read properties of undefined (reading 'profile')
    at ProfileColumnStateActions.updateColumnSummary (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/ProfileColumnStateActions.ts:43:44)
    at /Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/DataModelerStateService.ts:180:33
    at /Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/BatchedStateUpdate.ts:91:41
    at Array.forEach (<anonymous>)
    at /Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/BatchedStateUpdate.ts:91:19
    at recipe (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/entity-state-service/EntityStateService.ts:101:11)
    at Immer.produce (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/node_modules/immer/src/core/immerClass.ts:94:14)
    at DerivedModelEntityService.updateState (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/entity-state-service/EntityStateService.ts:98:14)
    at BatchedStateUpdate.batchUpdateState (/Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/BatchedStateUpdate.ts:89:13)
    at /Users/hamiltonulmer/Code/rill/data-modeler-prototype/src/common/data-modeler-state-service/BatchedStateUpdate.ts:53:18
[ERROR] 12:45:19 TypeError: Cannot read properties of undefined (reading 'profile')
```

### LINKED ISSUE #611: deleting a model that is linked to a metrics def causes issues when you click back on the metrics def

### LINKED ISSUE #646: if I delete a model powering a dashboard, I can still go to the dashboard, which is broken
- I would expect to not be able to get to the dashboard if the model is not properly configured for the config
- if I'm on a dashboard and I delete the underlying model on the left sidebar, I would expect it to switch back to the metrics config

### PR DESCRIPTION
**Pull request by AdityaHegde**
closes #610, closes #611, closes #646
Pushing an error message to notification centre when a model associated with a metrics explore is deleted.
@hamilton Dont think this is the best way to surface this error. Lemme know how you feel.

### CODE REVIEW

File: src/common/errors/ErrorMessages.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+// Unified location for error messages
+// TODO: move all errors here.
+
+export const ExploreSourceModelDoesntExist =
+  "Selected source model for the active metrics cube no longer exists";
```
Comment (bcolloran) [inline src/common/errors/ErrorMessages.ts:5]: It was decided that for now we will just use the terminology "metrics" instead of "metrics cube" (or the other options). We might change this in the future, but Mike wanted to go with that for

Comment (bcolloran) [reply src/common/errors/ErrorMessages.ts:5]: If we want to unify our error messages, I wonder if we would even want to use a string enum to contain them (for typing)? I'm not sure that is a good idea, just something that occurred to me

File: src/common/errors/ErrorMessages.ts [hunk 2]
```diff
@@ -0,0 +1,5 @@
+// Unified location for error messages
+// TODO: move all errors here.
+
+export const ExploreSourceModelDoesntExist =
```
Comment (bcolloran) [inline src/common/errors/ErrorMessages.ts:4]: i think we want to use `Explorer`  rather than `Explore`

**Review by bcolloran — CHANGES_REQUESTED** [review]
this looks fine overall to me, I only noticed a couple tiny things to be changed. As far as your question about how to surface the error, I don't have a strong feeling and will defer to Hamilton.

File: src/common/errors/ErrorMessages.ts (hunk 1 above)
Comment (AdityaHegde) [reply src/common/errors/ErrorMessages.ts:5]: Hmmm i was thinking of having functions in certain cases that handles messages that depend on variables. So depending on the message it will either be a constant or a funciton.

Comment (bcolloran) [reply src/common/errors/ErrorMessages.ts]: oh i see, that makes sense

**Review by bcolloran — APPROVED** [review]
looks fine to me, still deferring to @hamilton about the overall strategy

File: src/common/data-modeler-service/ApplicationActions.ts [hunk 3]
```diff
@@ -19,6 +20,18 @@ export class ApplicationActions extends DataModelerActions {
     entityType: EntityType,
     entityId: string
   ) {
+    const newActiveService = this.dataModelerStateService.getEntityStateService(
+      entityType,
+      StateType.Persistent
+    );
+    const newActiveAsset = newActiveService?.getById(entityId);
+    if (newActiveService && !newActiveAsset) {
+      console.log(entityType, entityId);
```
Comment (hamilton) [inline src/common/data-modeler-service/ApplicationActions.ts:29]:
```suggestion
```

File: src/common/data-modeler-state-service/ProfileColumnStateActions.ts [hunk 4]
```diff
@@ -23,6 +23,7 @@ export class ProfileColumnStateActions extends StateActions {
     entityId: string
   ): void {
     const entityToUpdate = stateService.getById(entityId, draftState);
+    if (!entityToUpdate) return;
```
Comment (hamilton) [inline src/common/data-modeler-state-service/ProfileColumnStateActions.ts:26]: why is this needed? can we add a comment?

File: src/common/data-modeler-state-service/ProfileColumnStateActions.ts [hunk 5]
```diff
@@ -40,6 +41,7 @@ export class ProfileColumnStateActions extends StateActions {
     summary: ProfileColumnSummary
   ): void {
     const entityToUpdate = stateService.getById(entityId, draftState);
+    if (!entityToUpdate) return;
```
Comment (hamilton) [inline src/common/data-modeler-state-service/ProfileColumnStateActions.ts:44]: same here ~ a comment here about this is useful

File: src/common/data-modeler-state-service/ProfileColumnStateActions.ts [hunk 6]
```diff
@@ -58,6 +60,7 @@ export class ProfileColumnStateActions extends StateActions {
     nullCount: number
   ): void {
     const entityToUpdate = stateService.getById(entityId, draftState);
+    if (!entityToUpdate) return;
```
Comment (hamilton) [inline src/common/data-modeler-state-service/ProfileColumnStateActions.ts:63]: and of course here too :)

File: src/lib/redux-store/utils/handleErrorResponse.ts [hunk 7]
```diff
@@ -0,0 +1,10 @@
+import type { ActionResponse } from "$common/data-modeler-service/response/ActionResponse";
+import { ActionStatus } from "$common/data-modeler-service/response/ActionResponse";
+import notifications from "$lib/components/notifications";
+
+export function handleErrorResponse(actionResponse: ActionResponse) {
+  if (!actionResponse || actionResponse.status === ActionStatus.Success) return;
+
+  const actionResponseMessage = actionResponse.messages[0];
+  notifications.send({ message: actionResponseMessage.message });
```
Comment (hamilton) [inline src/lib/redux-store/utils/handleErrorResponse.ts:9]: This is nice, but I think the better approach from a UX point of view would be to gray out the rest of the UX. I think this will take a bit of UX work to refactor to make it work out. Is there a status for the metrics definition that we could surface here? I would like to get rid of the quick start button and say that the model doesn't exist in its place.

**Review by hamilton — CHANGES_REQUESTED** [review]
The code looks great, thanks @AdityaHegde. I think this is surfacing a bunch of UX issues that we need to resolve. So if possible, when we have this error, could we have the metrics actually show this error message where the current `[quick start]` button is in the metrics config?

if this PR takes care of this, I can clean up the component / design.

File: src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte [hunk 8]
```diff
@@ -15,14 +15,21 @@
     createMetricsDefsApi,
     deleteMetricsDefsApi,
     fetchManyMetricsDefsApi,
+    validateSelectedSources,
   } from "$lib/redux-store/metrics-definition/metrics-definition-apis";
   import { getAllMetricsDefinitionsReadable } from "$lib/redux-store/metrics-definition/metrics-definition-readables";
   import { store } from "$lib/redux-store/store-root";
   import { getContext, onMount } from "svelte";
   import { slide } from "svelte/transition";
+  import { SourceModelValidationStatus } from "$common/data-modeler-state-service/entity-state-service/MetricsDefinitionEntityService.js";
```
Comment (hamilton) [inline src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte:24]: this is throwing an error in my code

File: src/common/data-modeler-service/ApplicationActions.ts [hunk 9]
```diff
@@ -19,6 +20,17 @@ export class ApplicationActions extends DataModelerActions {
...
     entityId: string
   ) {
+    const newActiveService = this.dataModelerStateService.getEntityStateService(
+      entityType,
+      StateType.Persistent
+    );
+    const newActiveAsset = newActiveService?.getById(entityId);
+    if (newActiveService && !newActiveAsset) {
+      return ActionResponseFactory.getErrorResponse(
+        new Error(`${entityType} with id ${entityId} doesnt exist.`)
```
Comment (hamilton) [inline src/common/data-modeler-service/ApplicationActions.ts:30]:
```
src/common/data-modeler-service/ApplicationActions.ts:30:9 - error TS2345: Argument of type 'Error' is not assignable to parameter of type 'Error & TypedError'.
  Property 'errorType' is missing in type 'Error' but required in type 'TypedError'.

30         new Error(`${entityType} with id ${entityId} doesnt exist.`)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/common/errors/TypedError.ts:4:3
    4   errorType: ActionErrorType;
        ~~~~~~~~~
    'errorType' is declared here.
```

**Review by hamilton — APPROVED** [review]
will wait for @magorlick to kick tires

**Comment by magorlick** [comment]
This looks good, thank you for the PR.  I noticed one small thing:

- If you remove 1 valid timeseries and there is another, it selects nothing.  We should should select the next timeseries in the order of the query output.
