### PR TITLE
Metrics reactivity based on source updates

### LINKED ISSUE #654: if a dashboard is open and I delete the associated model, it should switch back to the metrics config
Steps:
- go to a valid dashboard
- delete the model associated with the dashboard in the assets sidebar

Currently, the dashboard will get confused.

What we want is if the model disappears, the dashboard view should switch to the metrics config instead. That, paired with surfacing an error (done in #613), should be sufficient.

### LINKED ISSUE #658: Deleting Source powering Metrics doesn't surface meaningful feedback
**Describe the bug**
Deleting Source powering Metrics doesn't surface meaningful feedback.

**To Reproduce**
1. Upload a data set.
2. Create quick start models and metrics.
3. Delete the data set
4. No error messages are presented to the user, the dashboard doesn't work.
5. Kill the process in your terminal
6. Restart the Rill project
7. check the metrics config, note the Error messages for measures.
8. Add the data source back to the application
9. Check the metrics config, note that errors are still present even though the source has been restored.  The dashboard still doesn't work.

**Expected behavior**
Error messages should be useful and accurate.
- the issue here is the source is missing, the error is not at the measure-level to be most actionable.
- when the source returns errors should reactively update their understanding of upstream dependencies and remove errors.
If valid data is available, the user should always be able to navigate to the dashboard.

### PR DESCRIPTION
**Pull request by AdityaHegde**
closes #658 closes #654

1. Changes to sources updates validation on metrics definition.
2. If active entity was a metrics explorer and model validation failed, user is taken back to metrics definition.
3. Validation changes when model is deleted.
4. Automatically select 1st available timestamp when switching models.

We do not select the next valid timestamp column if the current one is invalid in this PR. Will address it in a later one.

### CODE REVIEW

**Comment by magorlick** [comment]
This is a nice step forward @AdityaHegde .  However, the error message reactively updates when I delete the source, however it is still indicating the model is the problem, not the source.

image

**Comment by AdityaHegde** [comment]
Its not easy to know the source is the problem without proper SQL parsing. Spending too much time on this without SQL parser might be wasted effort.

The error above says there is an error with the model. The user can go to the model and check what is wrong there.

File: src/routes/_surfaces/assets/TableAssets.svelte [hunk 1]
```diff
@@ -67,6 +74,14 @@
...
     );
   };
+
+  const deleteSource = (tableName: string) => {
+    deleteSourceApi(
+      tableName,
+      $persistentModelStore.entities,
+      $derivedModelStore.entities
+    );
+  };
```
Comment (bcolloran) [inline src/routes/_surfaces/assets/TableAssets.svelte:84]: vscode tells me that `deleteSourceApi` only needs one argument, has 3. Fixed it, which also removed th need for one import

Comment (AdityaHegde) [reply src/routes/_surfaces/assets/TableAssets.svelte:84]: Not sure why the build doesnt fail because of this

File: src/lib/redux-store/utils/invalidateExplorerThunk.ts [hunk 2]
```diff
@@ -29,16 +33,46 @@ export const invalidateExplorerThunk = <
...
+ * Non async thunk version that invalidates explorer
+ */
+export const invalidateExplorer = async <
+  Type extends EntityType,
+  Entity = EntityRecordMapType[Type][StateType.Persistent]
+>(
+  id: string,
+  changes: Partial<Entity>,
+  thunkAPI,
+  type: EntityType,
```
Comment (bcolloran) [inline src/lib/redux-store/utils/invalidateExplorerThunk.ts:59]: it looks like this arg `type` is not used, but that should not block merge

**Review by bcolloran — APPROVED** [review]
thanks for addressing that comment, let's merge it!
