### PR TITLE
fixes the source tooltip width in the wizard

### LINKED ISSUE #1088: fix width of GCS tooltip in source definition wizard

### PR DESCRIPTION
**Pull request by hamilton**
closes #1088 

- fixes tooltip widths
- removes a bit of copy that isn't needed

### CODE REVIEW

**Review by ericpgreen2 — APPROVED** [review]

**Comment by hamilton** [comment]
Going to wait for the copy merge then make some tweaks here to make it breath a little better.

File: web-local/src/lib/components/forms/InformationalField.svelte [hunk 1]
```diff
@@ -1,5 +1,6 @@
 <script lang="ts">
   import InfoCircle from "../icons/InfoCircle.svelte";
+  import LongDescription from "../tooltip/LongDescription.svelte";
```
Comment (ericpgreen2) [inline web-local/src/lib/components/forms/InformationalField.svelte:3]: I think there was a merge issue – this file doesn't exist

**Comment by ericpgreen2** [comment]
Looking so much better. There's unfortunate spacing with the period that follows the code snippet though: 
image

**Review by ericpgreen2 — APPROVED** [review]
