### PR TITLE
Redirect to metric def on dashboard error

### LINKED ISSUE #1144: Invalid dashboard states generate 404 errors instead of metrics configs screen with actionable error messages
**Describe the bug**
Seeing additional navigation related 404 errors user reports.
_"I wasn't able to use the model in the dashboard - kept getting 404s on the dashboard after it was created so I abandoned the task - I'll try again at some point"_

**Expected behavior**
Users should be taken to a metrics config screen when there is a human readable error and information on how to update the application to make the dashboard valid.

**Additional context**
https://twitter.com/reconbot/status/1586114999801741312?s=20&t=3h47b8qaigCs8vy54cPE1g

Related?
https://github.com/rilldata/rill-developer/issues/1133
https://github.com/rilldata/rill-developer/issues/1115
https://github.com/rilldata/rill-developer/issues/1117
https://github.com/rilldata/rill-developer/issues/1060

### PR DESCRIPTION
**Pull request by djbarnwal**
closes #1144 

404 message on Dashboard has been removed completely. In case of a dashboard error, we redirect to the metrics definition page. If the error is non standard, we show the message in a dialog box (standard message errors are shown in the components themselves).

### CODE REVIEW

**Review by hamilton — CHANGES_REQUESTED** [review]
Thank you for the PR!

I think we did not quite scope this right on the product side. This bug is a regression; previously, for a certain number of cases, we redirected the user back to the metrics config so they could fix the app-level issue. I think those error cases are (1) the model is invalid in some way or (2) the model / source does not exist. For other errors, we should be showing a 404 page with more descriptive information; I would opt for us to figure out how to show something in the window itself w/ 404 styling separately from this work.

That means we should support the following UX:
- if I have a dashboard link that doesn't show a dashboard, we should show a 404.
- if I delete the source that powers a dashboard, however, it should go back to the metrics page and show the errors that are provided by https://github.com/rilldata/rill-developer/blob/main/web-local/src/common/errors/ErrorMessages.ts#L7.

Apologies for not having given a more detailed rundown of the issue here. Would it be possible to update the existing PR with this in mind?

**Comment by magorlick** [comment]
Thank you for these changes.  I did another experience check and it feels like we have covered 2 and 3, however I am still taken to the first dashboard asset when I delete the dashboard I am looking at, not the 404 error (1).


https://user-images.githubusercontent.com/5587788/199504090-86f430a0-bf89-498c-a21f-3a513aab86c7.mp4



@hamilton , do you have a take on the way we are showing errors here vs across the application? I am not totally satisfied with this interaction. I think it is hard to troubleshoot an error when it is a full screen take over that needs to be closed and removed from the screen to take the next action.

**Comment by djbarnwal** [comment]
> Thank you for these changes. I did another experience check and it feels like we have covered 2 and 3, however I am still taken to the first dashboard asset when I delete the dashboard I am looking at, not the 404 error (1).

Well that's how it should be right? If I delete some asset (be it source, model or dashboard) I would want the next available asset (or the onboarding screen) to be selected. 404 errors shouldn't be a part of general workflow. Redirecting to 404 after a dashboard is deleted seems like a bad experience. Thoughts @hamilton ?

**Comment by hamilton** [comment]
@djbarnwal I see; I understand both sides here. If we delete a dashboard, going to another dashboard is a bit jarring since it's not always obvious what happened for the user. Additionally, throwing a 404 may also be a bit confusing because the user just did a normal thing.

A better option her would be to redirect to the model that powered the dashboard and pop up a notifcation saying that the dashboard is deleted using out `notification` store.

I haven't checked yet, but I think we should not be using modals for metrics config errors. I would rather see the error show up in the current red callout that we have for metrics generally. A modal is hard to deal with because I have to explicitly close it before doing anything and then I don't have the information I need to fix it.

File: web-local/src/common/errors/ErrorMessages.ts [hunk 1]
```diff
@@ -12,6 +12,8 @@ export const ExplorerSourceModelIsInvalid = "Model query has errors.";
 export const ExplorerTimeDimensionDoesntExist =
   "Previously selected timestamp column does not exist.";
 export const ExplorerSourceColumnDoesntExist = "not found in FROM clause!"; // the full DuckDB error message is `Binder Error: Referenced column "COLUMN_NAME" not found in FROM clause!`
+export const ExplorerDashboardDoesntExist =
+  "Cannot read properties of undefined (reading 'id')";
```
Comment (AdityaHegde) [inline web-local/src/common/errors/ErrorMessages.ts:16]: Please update the backend code to handle this instead of checking for reference error.

File: web-local/src/lib/components/modal/ModalContainer.svelte [hunk 2]
```diff
@@ -61,10 +61,12 @@
     initiateOnMount(container);
 
   onDestroy(() => {
-    modal.deactivate();
-    unlockBodyScrolling(container);
-    if (typeof originalTrigger?.focus === "function") {
-      setTimeout(() => originalTrigger.focus());
+    if (modal) {
```
Comment (AdityaHegde) [inline web-local/src/lib/components/modal/ModalContainer.svelte:64]: A cleaner way is to add,
```
if (!modal) return;
...
```

File: web-local/src/routes/(application)/dashboard/[id]/+page.ts [hunk 3]
```diff
@@ -26,21 +22,14 @@ export async function load({ params }) {
...
-      ExplorerSourceModelIsInvalid,
-      ExplorerSourceColumnDoesntExist,
-    ];
-
-    // if dashboard is invalid, redirect to the metrics definition page
     if (
-      invalidDashboardErrors.some(
-        (errMsg) => errMsg.includes(err.message) || err.message.includes(errMsg)
-      )
+      ExplorerDashboardDoesntExist.includes(err.message) ||
```
Comment (AdityaHegde) [inline web-local/src/routes/(application)/dashboard/[id]/+page.ts:26]: Update the backend to correctly return `ExplorerMetricsDefinitionDoesntExist` and handle that here.

File: web-local/src/routes/(application)/dashboard/[id]/edit/+page.ts [hunk 4]
```diff
@@ -34,6 +37,18 @@ export async function load({ params }) {
       return {
         metricsDefId: params.id,
       };
+    } else {
+      if (
+        ExplorerDashboardDoesntExist.includes(err.message) ||
```
Comment (AdityaHegde) [inline web-local/src/routes/(application)/dashboard/[id]/edit/+page.ts:42]: Use ExplorerMetricsDefinitionDoesntExist

**Review by AdityaHegde — APPROVED** [review]
Code wise this looks good!

File: web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte [hunk 5]
```diff
@@ -105,21 +109,18 @@
...
+      $applicationStore.activeEntity.id === metricsDef.id
     ) {
-      const nextMetricsDefId = getNextEntityId($metricsDefinitions, id);
-
-      if (nextMetricsDefId) {
-        goto(`/dashboard/${nextMetricsDefId}`);
-      } else {
-        goto("/");
-      }
+      goto(`/model/${metricsDef.sourceModelId}`);
```
Comment (djbarnwal) [inline web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte:117]: @AdityaHegde oddly this doesn't seem to work. Any clue what might be happening?

Comment (AdityaHegde) [reply web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte:117]: You need to delete the code in metrics-definition-api that does somewhat similar thing or move this there.

**Review by hamilton — APPROVED** [review]
