### PR TITLE
Fixing deletion on 1st asset

### LINKED ISSUE #973: deleting a currently-active model (the first one in the model assets list) does not redirect to another model
The SvelteKit routing has introduced a bug where if I delete an active model that happens to be the first model in the assets list, the interface isn't sure what to do.

### PR DESCRIPTION
**Pull request by AdityaHegde**
closes #973
Reusing existing code to handle deletion of an active entity.

### CODE REVIEW

File: web-local/src/lib/components/assets/TableAssets.svelte [hunk 1]
```diff
@@ -106,14 +107,11 @@
     }
   };
 
-  const deleteSource = (tableName: string) => {
-    const currentAssetIndex = $persistentTableStore.entities.findIndex(
-      (entity) => entity.tableName === tableName
-    );
+  const deleteSource = (tableName: string, id: string) => {
```
Comment (ericpgreen2) [inline web-local/src/lib/components/assets/TableAssets.svelte:110]: We can remove this `tableName` parameter now

**Review by ericpgreen2 — APPROVED** [review]
This is great. Just made one small comment you can address before merging.

File: web-local/src/lib/components/assets/TableAssets.svelte (hunk 1 above)
Comment (AdityaHegde) [reply web-local/src/lib/components/assets/TableAssets.svelte:110]: It used to delete the table in `deleteSourceApi`
