### PR TITLE
confirm prompt on local changes

### LINKED ISSUE #2098: Deploy: Fail deployment if the project directory has uncommitted changes

### PR DESCRIPTION
**Pull request by k-anshul**
closes #2098 

Prompts a user for confirmation in case there are changes in local repository.

### CODE REVIEW

File: cli/cmd/deploy/deploy.go [hunk 1]
```diff
@@ -473,6 +486,63 @@ func extractGitRemote(projectPath string) (string, error) {
 	return gitutil.RemotesToGithubURL(remotes)
 }
 
+func isLocalInSyncWithRemote(repoPath, branch string) error {
```
Comment (begelundmuller) [inline cli/cmd/deploy/deploy.go:489]: 1. Move to `package gitutil`
2. Seems like it's overloading `error` to provide a status. Maybe refactor to `gitutil.SyncStatus(path, branch string) (SyncStatus, error)`?

File: cli/cmd/deploy/deploy.go [hunk 2]
```diff
@@ -136,6 +137,18 @@ func DeployCmd(cfg *config.Config) *cobra.Command {
 				prodBranch = ghRes.DefaultBranch
 			}
 
+			// check there are no local changes
+			err = isLocalInSyncWithRemote(projectPath, prodBranch)
+			var gitSync *gitSyncError
+			if err != nil && errors.As(err, &gitSync) {
+				msg := gitSync.Error() + ". These changes will not be present in deployed project. Confirm deploy."
```
Comment (begelundmuller) [inline cli/cmd/deploy/deploy.go:144]: Better to do a `switch` and construct the full output here – makes it easier to understand what the user will see and edit language

**Review by begelundmuller — CHANGES_REQUESTED** [review]

File: cli/cmd/deploy/deploy.go [hunk 3]
```diff
@@ -413,6 +418,28 @@ func createProjectFlow(ctx context.Context, client *adminclient.Client, req *adm
...
+	msg := ""
+	switch syncStatus {
+	case gitutil.NA:
+		return true
+	case gitutil.SYNCED:
+		return true
+	case gitutil.MODIFIED:
+		msg = "Some files have been locally modified. These changes will not be present in deployed project. Confirm deploy."
+	case gitutil.AHEAD:
+		msg = "Local commits are not pushed to remote yet. These changes will not be present in deployed project. Confirm deploy."
```
Comment (begelundmuller) [inline cli/cmd/deploy/deploy.go:437]: Does it look weird to have such long prompts? Maybe it should print these as info (except for `Confirm deploy.`), then have the prompt on the next line just say `"Do you want to continue"`?

File: cli/pkg/gitutil/gitutil.go [hunk 4]
```diff
@@ -132,3 +132,63 @@ func SplitGithubURL(githubURL string) (account, repo string, ok bool) {
...
 }
+
+type SyncStatus int
+
+const (
+	NA       SyncStatus = iota
+	MODIFIED            // Local branch has untracked/modified changes
+	AHEAD               // Local branch is ahead of remote branch
+	SYNCED              // Local branch is in sync with remote branch
+)
```
Comment (begelundmuller) [inline cli/pkg/gitutil/gitutil.go:143]: Doesn't feel like an idiomatic Go enum:

1. Use "unspecified" instead of "NA"
2. Enums should be pascal case, not uppercase
3. They would also usually include the type name (before or after)

For example:

```
SyncStatusUnspecified
SyncStatusModified
SyncStatusAhead
SyncStatusSynced
```

(The Go authors recommendation is to have the type name after, if contextually relevant, but I always found that hard to navigate in autocomplete)

File: cli/pkg/gitutil/gitutil.go [hunk 5]
```diff
@@ -132,3 +132,63 @@ func SplitGithubURL(githubURL string) (account, repo string, ok bool) {
...
+
+// GetSyncStatus returns the status of current branch as compared to remote
+// Need to implement cases like local branch is behind/diverged from remote branch
```
Comment (begelundmuller) [inline cli/pkg/gitutil/gitutil.go:146]: Add `TODO: ` here

**Review by begelundmuller — CHANGES_REQUESTED** [review]

File: cli/cmd/deploy/deploy.go (hunk 3 above)
Comment (k-anshul) [reply cli/cmd/deploy/deploy.go:437]: Yeah even I am also not sure. Having all msg in the prompt is good for context. Splitting it in multiple lines also seems good. I will split as you are suggesting.

File: cli/pkg/gitutil/gitutil.go (hunk 4 above)
Comment (k-anshul) [reply cli/pkg/gitutil/gitutil.go:143]: 1. Unknown/unspecified/NA all seem to specify the same meaning and the difference is usually subjective. 
3. I think Go authors are not consistent here. I get an impressions at multiple places that the general recommendation is to be as less verbose as possible. I personally have seen so many examples of enums not putting the type name either before or after. Example here : https://github.com/google/go-cloud/blob/04a775a88f1cb11f0d8d9131d1de9d5a6843b355/internal/gcerr/gcerr.go#L36
I would prefer it to be short.

**Review by begelundmuller — APPROVED** [review]
