### PR TITLE
Show fetching status for null profile

### LINKED ISSUE #1591: Profiling flickers incorrect values for percent NULL
**Describe the bug**
Profiling flickers incorrect values for percent NULL when editing query

**To Reproduce**
1. upload a data set with 250+rows
2. create a model and change the `LIMIT` rapidly
3. See the null percentages in the profiles flicker incorrect values

**Expected behavior**
I only expect an animation between the current value and the subsequent value - never an impossible or misleading value.

Watch the profiling for `TRANSIT_DISTRICT` in this video:
https://user-images.githubusercontent.com/5587788/211678732-0dc5e0be-c997-4b43-a4f1-f9e808e6c829.mp4

### PR DESCRIPTION
**Pull request by djbarnwal**
Closes #1591

### CODE REVIEW

**Comment by hamilton** [comment]
tagging @ericpgreen2 for code review

**Review by ericpgreen2 — APPROVED** [review]
Code looks good

File: web-local/src/lib/components/column-profile/column-types/sparks/NullPercentageSpark.svelte [hunk 1]
```diff
@@ -9,6 +9,7 @@
   export let type: string;
   export let nullCount: number;
   export let totalRows: number;
+  export let isFetching: boolean;
 
   $: percentage = nullCount / totalRows;
```
Comment (hamilton) [inline web-local/src/lib/components/column-profile/column-types/sparks/NullPercentageSpark.svelte:14]: I think this is _almost_ right; the issue here, though, is that we should only update the number if both the nullCount & totalRows are both updating (in other words, `isFetching === false`). I would maybe opt to change this to 
```suggestion
  $: if(!isFetching) percentage = nullCount / totalRows;
```

And get rid of the templated check with the `..%`. Otherwise this is actually a design tweak. The default value of `percentage` should be `undefined` in that case, should not show anything in the template.

**Review by hamilton — CHANGES_REQUESTED** [review]
this is close from a UX pov ~ try the suggested change and let me know if that fixes the issue while not introducing `..%`

File: web-local/src/lib/components/column-profile/column-types/sparks/NullPercentageSpark.svelte (hunk 1 above)
Comment (djbarnwal) [reply web-local/src/lib/components/column-profile/column-types/sparks/NullPercentageSpark.svelte]: Made the change. Also added a check for `percentage <=1` as there were cases when percentage momentarily became >100% when editing the model quickly.

Comment (hamilton) [reply web-local/src/lib/components/column-profile/column-types/sparks/NullPercentageSpark.svelte]: Thanks! I'll take a look now.

**Review by hamilton — APPROVED** [review]

**Comment by hamilton** [comment]
Thanks @djbarnwal! This is great.
