### PR TITLE
removes leaderboards that are not valid

### LINKED ISSUE #703: Invalid dimensions in metrics config are shown on downstream dashboards
**Describe the bug**
When you remove a dimension from the model file the dashboard is still presenting the missing dimension with "no available values". 

**To Reproduce**
1. init the example and quick start to a dashboard
2. Update model transform to SELECT * EXCLUDE (dimension)
3. look at dashboard leaderboards
4. See the dimension still present with "no available values". 

**Expected behavior**
We should remove leaderboards and dimensions that are not valid. It is not clear if all the values are null or the dimension is not available at the dashboard level.

### PR DESCRIPTION
**Pull request by hamilton**
closes #703

### CODE REVIEW

File: src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte [hunk 1]
```diff
@@ -29,6 +33,9 @@
   let metricsExplorer: Readable<MetricsExplorerEntity>;
   $: metricsExplorer = getMetricsExplorerById(metricsDefId);
 
+  let dimensions: Readable<DimensionConfiguration>;
+  $: dimensions = getDimensionsByMetricsId(metricsDefId);
```
Comment (djbarnwal) [inline src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte:37]: VS Code is prompting a type error here for me - 

```
Type 'Readable<DimensionDefinitionEntity[]>' is not assignable to type 'Readable<DimensionConfiguration>'.
  Type 'DimensionDefinitionEntity[]' is missing the following properties from type 'DimensionConfiguration': name, field, id
```

File: src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte [hunk 2]
```diff
@@ -104,6 +111,20 @@
   onDestroy(() => {
     observer?.disconnect();
   });
+
+  /** Filter out the leaderboards whose underlying dimensions do not pass the validation step. */
+  $: validDimensions =
```
Comment (djbarnwal) [inline src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte:116]: Let's also use `validDimensions` in `leaderboardFormatScale` instead of `$metricsExplorer.leaderboards`

**Review by djbarnwal — CHANGES_REQUESTED** [review]

**Review by djbarnwal — APPROVED** [review]
Looks good!
