### PR TITLE
Fix ingestion of files with number and hypen

### LINKED ISSUE #762: file names that are entirely numbers and symbols fail
**Describe the bug**
When you ingest a file name that is entirely numbers and symbols the ingestion fails.

**To Reproduce**
1. Start with a csv or parquet file you know works in Rill Developer
2. Change the name to '2022-08-09'
3. Try to import the file
5. Change the name to '2022-08-09_data'
6. Try to import the file
7. File ingests

**Expected behavior**
File names should be sanitized for the user so they can be ingested as a source.

### PR DESCRIPTION
**Pull request by djbarnwal**
Fixes #762

### CODE REVIEW

File: web-local/src/lib/util/extract-table-name.ts [hunk 1]
```diff
@@ -6,9 +6,17 @@ export function getTableNameFromFile(filePath: string, name?: string) {
 }
 
 export function extractTableName(filePath: string): string {
-  const fileName = filePath.split(FILE_PATH_SPLIT_REGEX).slice(-1)[0];
+  let fileName = filePath.split(FILE_PATH_SPLIT_REGEX).slice(-1)[0];
   const lastIndexOfDot = fileName.lastIndexOf(".");
-  return lastIndexOfDot >= 0 ? fileName.substring(0, lastIndexOfDot) : fileName;
+  fileName =
```
Comment (AdityaHegde) [inline web-local/src/lib/util/extract-table-name.ts:11]: Can you add tests to ExtractTableName.spec.ts to verify these changes?

**Review by AdityaHegde — CHANGES_REQUESTED** [review]

**Review by AdityaHegde — APPROVED** [review]
