### PR TITLE
Stopping table sync if it is profiling already

### LINKED ISSUE #230: Importing a table seems to reset profiling part-way through
**Describe the bug**
I'm seeing that when I import a table right now, profiling wiill kick off, then get interrupted and start over. I am not sure if this is due to the table scans or what.

**To Reproduce**
1. start a new Rill Developer project
2. drag and drop a parquet or csv into the tables section on the assets pane. A bigger dataset is better, like the nyc311 dataset or the sf311 dataset.
3. watch it import fine
4. see that it starts profilng the columns, then interrupts itself and starts over.

### PR DESCRIPTION
**Pull request by AdityaHegde**
Fixes #230
Adding a check in table sync to not run when it is profiling.

### CODE REVIEW

File: src/routes/_surfaces/assets/TableAssets.svelte [hunk 1]
```diff
@@ -55,7 +55,7 @@
   <div
     class="pb-6"
     transition:slide|local={{ duration: 200 }}
-    on:drop={onSourceDrop}
+    on:drop|preventDefault|stopPropagation={onSourceDrop}
```
Comment (AdityaHegde) [inline src/routes/_surfaces/assets/TableAssets.svelte:58]: This fixes an issue where uploading also downloads the file.

**Comment by bcolloran** [comment]
looks good to me  @AdityaHegde

**Review by bcolloran — APPROVED** [review]
