### PR TITLE
Catch return on search

### LINKED ISSUE #1137: dimension search should `preventDefault` when the `return` key is pressed
Noticed this last night when I was searching for strings in a very long dataset.

We need to catch `return`. As is, it will press the `All Dimensions` button. This video doesn't show the keypress but it gives you a sense of how to reproduce

Kapture 2022-10-28 at 05 55 44

### PR DESCRIPTION
**Pull request by djbarnwal**
Fixes #1137 

Also fixes the case when no dimension column header is show if search results is 0.

### CODE REVIEW

File: web-local/src/lib/components/search/Search.svelte [hunk 1]
```diff
@@ -9,6 +9,13 @@
   /* Input value being searched */
   export let value;
 
+  function handleKeyDown(event) {
+    if (event.code == "Enter") {
+      event.preventDefault();
+      return false;
+    }
```
Comment (djbarnwal) [inline web-local/src/lib/components/search/Search.svelte:16]: Wondering if this is the best way to handle this. Probably there is more elegant svelte way of handling this @hamilton ?

Comment (hamilton) [reply web-local/src/lib/components/search/Search.svelte:16]: I think this seems like a pretty sensible solution! We don't want to `preventDefault` in any other case (for instance tabbing away from search)

**Review by hamilton — APPROVED** [review]
