### PR TITLE
fixes UI issues with nested structs

### LINKED ISSUE #1862: UI breaks on nested JSON source in DuckDB 0.7.1
I ran into this when testing the DuckDB 0.7.1 PR (https://github.com/rilldata/rill-developer/pull/1859) – though at first glance, it appears unrelated to the DuckDB upgrade. Since another bug was blocking the source from ingesting, to replicate the bug described below, you will need to test on that branch until it's merged.

The UI breaks (doesn't show data, doesn't respond to clicks, shows infinite loading spinners) on this source `roda.yaml`:
```
type: "s3"
region: "us-east-1"
uri: "s3://registry.opendata.aws/roda/ndjson/*.ndjson"
```

Here's a screenshot of the UI and the inspector:

Screenshot 2023-03-03 at 14 54 14

I have tried various things to debug the problem. The `d3-interpolate-path` error in the screenshot above is the only one that consistently shows up. 

I also managed to find a network request where it was requesting `topk` profiling with `"columnName":"1"` (the dataset does not have a column named `"1"`). Maybe it's treating an array as an object somewhere?

### PR DESCRIPTION
**Pull request by hamilton**
fixes #1862

### CODE REVIEW

File: web-common/src/components/column-profile/sort-utils.ts [hunk 1]
```diff
@@ -63,6 +63,12 @@ export function sortByName(a, b) {
 export function defaultSort(a, b) {
   const byType = sortByType(a, b);
   if (byType !== 0) return byType;
+  /** sort nested types by cardinality, regardless of type. This should indicate
+   * to the user if the nested type could easily be unnested into another simple column type
+   * (e.g. low cardinality nested types may be better expressed as a VARCHAR or INTEGER)
+   */
+  if (isNested(a.type) && isNested(a.type)) return sortByCardinality(a, b);
```
Comment (djbarnwal) [inline web-common/src/components/column-profile/sort-utils.ts:70]: This should just be `isNested(a.type)` right?

**Review by magorlick — APPROVED** [review]
worked for me! Thanks

**Review by djbarnwal — APPROVED** [review]
Looks good, have left a small nit comment post which this can be merged. Approving.
